name: Manual Deploy

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: environment

jobs:
  check_actor:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
     - uses: actions/github-script@v7
       with:
         script: |
           const authorizedUsers = JSON.parse(vars.AUTHORIZED_USERS);
           const actor = context.actor;
           if (!authorizedUsers.includes(actor)) {
             core.setFailed(`Actor ${actor} is not authorized to run this workflow.`);
           }
       env:
         AUTHORIZED_USERS: ${{ vars.AUTHORIZED_USERS }}

  deploy:
    needs: check_actor  

    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Code Checkout
      uses: actions/checkout@v3

    # - name: Setup .NET 7
    #   uses: actions/setup-dotnet@v3
    #   with:
    #     dotnet-version: 7.0.x

    # - name: Restore Dependencies
    #   run: dotnet restore WebApp.sln

    # - name: Build API
    #   run: dotnet build WebApp/WebApp.csproj --no-restore

    - name: Deploy
      run: echo "Deployement to ${{ inputs.environment }}"