name: Manual Deploy

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: environment

jobs:
  check_actor:
    runs-on: ubuntu-latest
    steps:
      - name: Terminate workflow if actor is not authorized
        run: |
          if [[ ! " ${AUTHORIZED_USERS[@]} " =~ " ${ACTOR} " ]]; then
            echo "Actor ${ACTOR} is not authorized to run this workflow."
            exit 1
          fi
        env:
          ACTOR: ${{ github.actor }}
          AUTHORIZED_USERS: ${{ fromJSON(secrets.AUTHORIZED_USERS) }}

  deploy:
    needs: check_actor  

    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Code Checkout
      uses: actions/checkout@v3

    # - name: Setup .NET 7
    #   uses: actions/setup-dotnet@v3
    #   with:
    #     dotnet-version: 7.0.x

    # - name: Restore Dependencies
    #   run: dotnet restore WebApp.sln

    # - name: Build API
    #   run: dotnet build WebApp/WebApp.csproj --no-restore

    - name: Deploy
      run: echo "Deployement to ${{ inputs.environment }}"